# Generated by Django 4.2.11 on 2024-03-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0003_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='action', max_length=200, unique=True),
        ),
    ]
