# Generated by Django 4.2.10 on 2024-02-26 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trophy_hunter', '0003_alter_game_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rarity'],
            },
        ),
        migrations.RenameField(
            model_name='game',
            old_name='trophies',
            new_name='trophy_count',
        ),
        migrations.DeleteModel(
            name='Trophies',
        ),
        migrations.AddField(
            model_name='trophy',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='trophy_hunter.game'),
        ),
    ]
