# Generated by Django 4.2.10 on 2024-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0004_trophy_rename_trophies_game_trophy_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='action', max_length=200, unique=True),
        ),
    ]
