# Generated by Django 4.2.11 on 2024-03-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0004_trophy_rename_trophies_game_trophy_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(default='horror', on_delete=django.db.models.deletion.CASCADE, to='trophy_hunter.game')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophy_hunter.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophy_hunter.genres')),
            ],
        ),
    ]
