# Generated by Django 4.2.10 on 2024-03-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0005_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
