# Generated by Django 4.2.11 on 2024-03-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0006_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophy_hunter.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophy_hunter.genre')),
            ],
        ),
    ]
