# Generated by Django 4.2.10 on 2024-03-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0006_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trophy_hunter.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='trophy_hunter.genre')),
            ],
        ),
    ]
