# Generated by Django 4.2.10 on 2024-03-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0007_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='action', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='trophy_hunter.genre'),
        ),
    ]
