# Generated by Django 4.2.11 on 2024-03-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0007_trophies_slug_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_score',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='guide',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_guide', to='trophy_hunter.game'),
        ),
    ]
