# Generated by Django 4.2.11 on 2024-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0007_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophies',
            name='slug',
            field=models.SlugField(default='trophy-slug', max_length=200),
        ),
    ]
