# Generated by Django 4.2.11 on 2024-04-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='trophy',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='trophy_comments', to='trophy_hunter.trophies'),
        ),
    ]
