# Generated by Django 4.2.11 on 2024-04-12 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trophy_hunter', '0013_comment_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='likes',
            field=models.ManyToManyField(related_name='guide_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
