# Generated by Django 4.2.11 on 2024-04-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0016_remove_comment_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='placeholder', max_length=200, unique=True),
        ),
    ]
