# Generated by Django 4.2.11 on 2024-04-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0017_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
