# Generated by Django 4.2.11 on 2024-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy_hunter', '0018_remove_comment_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='trophies',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
